Repository wildhamsters/battleships, pull requests merged in 2022-05, with the labels that each got.

#116 Starting player is chosen randomly
  src/main/java/org/wildhamsters/battleships/ConnectedPlayers.java
  src/main/java/org/wildhamsters/battleships/GameService.java
  src/main/java/org/wildhamsters/battleships/WebSocketController.java
  src/main/resources/static/app.js
Labels: enhancement

#134 Create welcome page
  src/main/java/org/wildhamsters/battleships/RegistrationController.java
  src/main/java/org/wildhamsters/battleships/WebSecurityConfig.java
  src/main/resources/static/register.html
  src/main/resources/static/welcome.css
  src/main/resources/static/welcome.html
Labels: enhancement, frontend

#136 [FIX] Error page quick fix
  pom.xml
  src/main/java/org/wildhamsters/battleships/RegistrationController.java
  src/main/java/org/wildhamsters/battleships/WebConfig.java
  src/main/resources/static/404.html
Labels: bug, frontend

#137 Show buttons after the game ends
  src/main/resources/static/app.js
  src/main/resources/static/index.html
  src/main/resources/static/stylesheet.css
Labels: frontend

#138 Integration test rework
  src/main/java/org/wildhamsters/battleships/configuration/GameConfigurer.java
  src/main/java/org/wildhamsters/battleships/configuration/GameSettings.java
  src/main/java/org/wildhamsters/battleships/fleet/Fleet.java
  src/main/java/org/wildhamsters/battleships/fleet/ShipCondition.java
  src/test/java/org/wildhamsters/battleships/BattleshipsIT.java
  src/test/java/org/wildhamsters/battleships/configuration/ConfigurationIT.java
Labels: test

#141 Send logs to elk
  src/main/java/org/wildhamsters/battleships/GameService.java
  src/main/java/org/wildhamsters/battleships/Log.java
  src/main/java/org/wildhamsters/battleships/Logger.java
  src/main/java/org/wildhamsters/battleships/RegistrationController.java
  src/main/java/org/wildhamsters/battleships/UserService.java
Labels: documentation, enhancement
